services:
  - type: web
    name: chaincheck-backend
    env: node
    region: oregon
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
