services:
  - type: web
    name: chaincheck-backend
    env: node
    region: oregon
    branch: main
    buildCommand: NODE_ENV=development npm install && npm run build
    startCommand: npm start
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production  # Only for runtime, since buildCommand overrides NODE_ENV