services:
  - type: web
    name: chaincheck-backend
    env: node
    region: oregon
    branch: main
    buildCommand: NODE_ENV=development npm install && npm run build
    startCommand: NODE_ENV=production npm start
    plan: starter